openapi: 3.1.1
info:
  title: fastify-boilerplate
  description: ""
  version: 0.0.1
components:
  schemas:
    def-0:
      type: object
      required:
        - message
        - error
      properties:
        message:
          type: string
        error:
          type: string
        code:
          type: string
        statusCode:
          type: string
      title: error
    def-1:
      title: MqttStats
      description: Statistics about the MQTT client connection status
      type: object
      required:
        - connected
        - reconnecting
        - client_id
      properties:
        connected:
          type: boolean
        reconnecting:
          type: boolean
        client_id:
          type: string
    def-2:
      type: object
      required:
        - username
        - email
        - password
      properties:
        user_id:
          format: uuid
          type: string
        username:
          minLength: 1
          maxLength: 255
          type: string
        email:
          format: email
          maxLength: 255
          type: string
        first_name:
          anyOf:
            - maxLength: 255
              type: string
            - type: "null"
        last_name:
          anyOf:
            - maxLength: 255
              type: string
            - type: "null"
        password:
          minLength: 8
          type: string
      title: userWithPassword
    def-3:
      type: object
      required:
        - username
        - email
      properties:
        user_id:
          format: uuid
          type: string
        username:
          minLength: 1
          maxLength: 255
          type: string
        email:
          format: email
          maxLength: 255
          type: string
        first_name:
          anyOf:
            - maxLength: 255
              type: string
            - type: "null"
        last_name:
          anyOf:
            - maxLength: 255
              type: string
            - type: "null"
      title: user
    def-4:
      type: object
      required:
        - id
      properties:
        id:
          format: uuid
          type: string
      title: idParam
paths:
  /api/v1/health/mqtt/:
    get:
      tags:
        - health
      description: Mqtt Client Health check
      responses:
        "200":
          description: Statistics about the MQTT client connection status
          content:
            application/json:
              schema:
                title: MqttStats
                description: Statistics about the MQTT client connection status
                type: object
                required:
                  - connected
                  - reconnecting
                  - client_id
                properties:
                  connected:
                    type: boolean
                  reconnecting:
                    type: boolean
                  client_id:
                    type: string
        "503":
          description: Statistics about the MQTT client connection status
          content:
            application/json:
              schema:
                title: MqttStats
                description: Statistics about the MQTT client connection status
                type: object
                required:
                  - connected
                  - reconnecting
                  - client_id
                properties:
                  connected:
                    type: boolean
                  reconnecting:
                    type: boolean
                  client_id:
                    type: string
  /api/v1/health/status/:
    get:
      tags:
        - health
      description: Health check
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Health status
                    example: ok
  /api/v1/health/teapot/:
    get:
      tags:
        - health
      description: Teapot
      responses:
        "418":
          description: https://www.rfc-editor.org/rfc/rfc9110#section-15.5.19
          content:
            application/json:
              schema:
                type: string
                description: https://www.rfc-editor.org/rfc/rfc9110#section-15.5.19
                example: I'm a teapot
  /api/v1/users/{id}:
    get:
      tags:
        - user
      description: Gets a user for a given id
      parameters:
        - schema:
            format: uuid
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - username
                  - email
                properties:
                  user_id:
                    format: uuid
                    type: string
                  username:
                    minLength: 1
                    maxLength: 255
                    type: string
                  email:
                    format: email
                    maxLength: 255
                    type: string
                  first_name:
                    anyOf:
                      - maxLength: 255
                        type: string
                      - type: "null"
                  last_name:
                    anyOf:
                      - maxLength: 255
                        type: string
                      - type: "null"
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error
                properties:
                  message:
                    type: string
                  error:
                    type: string
                  code:
                    type: string
                  statusCode:
                    type: string
    put:
      tags:
        - user
      description: Update the user with the ID specified in the URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
              properties:
                user_id:
                  format: uuid
                  type: string
                username:
                  minLength: 1
                  maxLength: 255
                  type: string
                email:
                  format: email
                  maxLength: 255
                  type: string
                first_name:
                  anyOf:
                    - maxLength: 255
                      type: string
                    - type: "null"
                last_name:
                  anyOf:
                    - maxLength: 255
                      type: string
                    - type: "null"
      parameters:
        - schema:
            format: uuid
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - username
                  - email
                properties:
                  user_id:
                    format: uuid
                    type: string
                  username:
                    minLength: 1
                    maxLength: 255
                    type: string
                  email:
                    format: email
                    maxLength: 255
                    type: string
                  first_name:
                    anyOf:
                      - maxLength: 255
                        type: string
                      - type: "null"
                  last_name:
                    anyOf:
                      - maxLength: 255
                        type: string
                      - type: "null"
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error
                properties:
                  message:
                    type: string
                  error:
                    type: string
                  code:
                    type: string
                  statusCode:
                    type: string
    delete:
      tags:
        - user
      description: Delete the user with the ID specified in the URL
      parameters:
        - schema:
            format: uuid
            type: string
          in: path
          name: id
          required: true
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - username
                  - email
                properties:
                  user_id:
                    format: uuid
                    type: string
                  username:
                    minLength: 1
                    maxLength: 255
                    type: string
                  email:
                    format: email
                    maxLength: 255
                    type: string
                  first_name:
                    anyOf:
                      - maxLength: 255
                        type: string
                      - type: "null"
                  last_name:
                    anyOf:
                      - maxLength: 255
                        type: string
                      - type: "null"
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error
                properties:
                  message:
                    type: string
                  error:
                    type: string
                  code:
                    type: string
                  statusCode:
                    type: string
  /api/v1/users/:
    post:
      tags:
        - user
      description: Create a user if it doesn't exist. Email and Username must be unique.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                user_id:
                  format: uuid
                  type: string
                username:
                  minLength: 1
                  maxLength: 255
                  type: string
                email:
                  format: email
                  maxLength: 255
                  type: string
                first_name:
                  anyOf:
                    - maxLength: 255
                      type: string
                    - type: "null"
                last_name:
                  anyOf:
                    - maxLength: 255
                      type: string
                    - type: "null"
                password:
                  minLength: 8
                  type: string
      responses:
        "200":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - username
                  - email
                properties:
                  user_id:
                    format: uuid
                    type: string
                  username:
                    minLength: 1
                    maxLength: 255
                    type: string
                  email:
                    format: email
                    maxLength: 255
                    type: string
                  first_name:
                    anyOf:
                      - maxLength: 255
                        type: string
                      - type: "null"
                  last_name:
                    anyOf:
                      - maxLength: 255
                        type: string
                      - type: "null"
        "404":
          description: Default Response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - error
                properties:
                  message:
                    type: string
                  error:
                    type: string
                  code:
                    type: string
                  statusCode:
                    type: string
