name: Run Tests
on:
    pull_request:
        branches: [main]

env:
    NODE_VERSION: 25

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run Tests
              # Ensure your test runner outputs a JUnit XML file
              run: npm run test-coverage

            - name: Upload Test Results
              uses: actions/upload-artifact@v4
              if: always() # Upload even if tests fail
              with:
                  name: junit-results
                  path: "**/junit.xml" # Adjust path to your results
                  retention-days: 1

            - name: Upload Coverage Results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: coverage-results
                  path: "**/cobertura-coverage.xml"
                  retention-days: 1

            - name: Save Event File
              if: always()
              run: cp "${{ github.event_path }}" event.json
            
            - name: Upload Event File
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: event-file
                  path: event.json
                  retention-days: 1
